/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;


 import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class FrmData extends javax.swing.JFrame {
    
    public Statement st;
    public ResultSet rs;
    Connection cn = koneksi.KoneksiDatabase.Bukakoneksi();
  
    public FrmData() {
        initComponents();
        Tampildata();
    }
    
    private void Bersih(){
    txtID.setText("");
    txtNAMADATA.setText("");
    txtJENISDATA.setText("");
    txtASALDATA.setText("");  
    
    btnSIMPAN.setText("Simpan");
    txtID.setEditable(true);
    }
    
    private void Caridata(){     
         try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * from isi_data where"
                    + cmbCari.getSelectedItem().toString()+"LIKE'%"
                    +txtCARI.getText()+"%'");
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No.");
            model.addColumn("ID");
            model.addColumn("NAMA_DATA");
            model.addColumn("JENIS_DATA");
            model.addColumn("ASAL_DATA");
            
            int no = 1;
            
       model.getDataVector().removeAllElements();
       model.fireTableDataChanged();
       model.setRowCount(0);
       
       while(rs.next()){
       Object[] data = {
           no ++,
       rs.getString("ID"),
           rs.getString("NAMA_DATA"),
           rs.getString("JENIS_DATA"),
           rs.getString("ASAL_DATA")
       };   
       model.addRow(data);
       tblDATA.setModel(model);
       }       
        }catch (Exception e){
        }
        
    }

    private void Tampildata(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * from isi_data ");
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No.");
            model.addColumn("ID");
            model.addColumn("NAMA_DATA");
            model.addColumn("JENIS_DATA");
            model.addColumn("ASAL_DATA");
            
            int no = 1;
            
       model.getDataVector().removeAllElements();
       model.fireTableDataChanged();
       model.setRowCount(0);
       
       while(rs.next()){
       Object[] data = {
           no ++,
       rs.getString("ID"),
           rs.getString("NAMA_DATA"),
           rs.getString("JENIS_DATA"),
           rs.getString("ASAL_DATA")
       };   
       model.addRow(data);
       tblDATA.setModel(model);
       }       
        }catch (Exception e){
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNAMADATA = new javax.swing.JTextField();
        txtJENISDATA = new javax.swing.JTextField();
        txtASALDATA = new javax.swing.JTextField();
        btnSIMPAN = new javax.swing.JButton();
        btnHAPUS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDATA = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnBATALKAN = new javax.swing.JButton();
        txtCARI = new javax.swing.JTextField();
        cmbCari = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("NAMA DATA");

        jLabel3.setText("JENIS DATA");

        jLabel4.setText("ASAL DATA");

        txtNAMADATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNAMADATAActionPerformed(evt);
            }
        });

        btnSIMPAN.setText("Simpan");
        btnSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIMPANActionPerformed(evt);
            }
        });

        btnHAPUS.setText("Hapus");
        btnHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAPUSActionPerformed(evt);
            }
        });

        tblDATA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama Data", "Jenis Data", "Asal Data"
            }
        ));
        tblDATA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDATAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDATA);

        jLabel5.setText("Cari");

        btnBATALKAN.setText("Batalkan");
        btnBATALKAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBATALKANActionPerformed(evt);
            }
        });

        txtCARI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCARIKeyPressed(evt);
            }
        });

        cmbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NAMA_DATA", " " }));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtJENISDATA, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtNAMADATA, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSIMPAN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHAPUS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBATALKAN))
                            .addComponent(txtASALDATA, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCARI, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNAMADATA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJENISDATA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtASALDATA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSIMPAN)
                    .addComponent(btnHAPUS)
                    .addComponent(btnBATALKAN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCARI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(801, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNAMADATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNAMADATAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNAMADATAActionPerformed

    private void btnSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIMPANActionPerformed
       try{
           st = cn.createStatement();
           if (txtID.getText().equals("")||txtNAMADATA.getText().equals("")||
                 txtJENISDATA.getText().equals("")||txtASALDATA.getText().equals("")  ){
               JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong", "validasi data", JOptionPane.INFORMATION_MESSAGE);
               return;
           }if (btnSIMPAN.getText()== "Simpan"){
               String cek = "select * from isi_data where ID = '" + txtID.getText()+"'";
               rs =st.executeQuery(cek);
               if(rs.next()){
                   JOptionPane.showMessageDialog(null, "Ups Sudah ada data");
               }else{
                   String sql ="insert into isi_data VALUES('"+txtID.getText()+
                           "','"+ txtNAMADATA.getText()+
                           "','"+ txtJENISDATA.getText()+
                           "','"+ txtASALDATA.getText()+"')";
                   st.executeUpdate(sql);
                   JOptionPane.showMessageDialog(null,"databerhasil disimpan");
                   Bersih();
                   Tampildata();
               }
           }else{   
               String update ="UPDATE isi_data set NAMA_DATA ='"+txtNAMADATA.getText()+
                           "',JENIS_DATA = '"+ txtJENISDATA.getText()+
                        "',ASAL_DATA = '"+ txtASALDATA.getText()+
                           "'where ID = '"+ txtID.getText()+"'";
                   st.executeUpdate(update);
                   JOptionPane.showMessageDialog(null,"databerhasil disimpan");
                   Bersih();
                   Tampildata();
           }
    }catch (Exception e) {
        JOptionPane.showConfirmDialog(null, e);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSIMPANActionPerformed

    private void tblDATAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDATAMouseClicked
      txtID.setText(tblDATA.getValueAt(tblDATA.getSelectedRow(), 1).toString());
      txtNAMADATA.setText(tblDATA.getValueAt(tblDATA.getSelectedRow(), 2).toString());  
       txtJENISDATA.setText(tblDATA.getValueAt(tblDATA.getSelectedRow(), 3).toString());
       txtASALDATA.setText(tblDATA.getValueAt(tblDATA.getSelectedRow(), 4).toString());
       
       txtID.setEditable(false);
       btnSIMPAN.setText("Ubah");
    }//GEN-LAST:event_tblDATAMouseClicked

    private void btnHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAPUSActionPerformed
      if (txtID.getText().equals("")){
          JOptionPane.showMessageDialog(this, "pilih data dulu!");
      }else{
          int jawab = JOptionPane.showConfirmDialog(null, "benarkah data ini yang akan dihapus?", "konfirmasi",JOptionPane.YES_NO_OPTION);
         if (jawab == 0){  
             try{
                 st = cn.createStatement();
                 String sql = "delete from isi_data where ID ='"+ txtID.getText()+"'";
                 st.executeUpdate(sql);
                 JOptionPane.showMessageDialog(null, "data berhasil dihapus!");
                 Tampildata();
                 Bersih();
             }catch (Exception e){
                     
             }
    }//GEN-LAST:event_btnHAPUSActionPerformed
      }
    }
    private void btnBATALKANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBATALKANActionPerformed
       Bersih();
    }//GEN-LAST:event_btnBATALKANActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtCARIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCARIKeyPressed
        Caridata();
    }//GEN-LAST:event_txtCARIKeyPressed
      
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBATALKAN;
    private javax.swing.JButton btnHAPUS;
    private javax.swing.JButton btnSIMPAN;
    private javax.swing.JComboBox<String> cmbCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDATA;
    private javax.swing.JTextField txtASALDATA;
    private javax.swing.JTextField txtCARI;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJENISDATA;
    private javax.swing.JTextField txtNAMADATA;
    // End of variables declaration//GEN-END:variables
}
